---
dataset: &dataset "pbvs25_thermal"
# Dataset name. It is also the name of the directory inside `data_dir`.
name: &camera_name "pbvs25"
# Camera name is also used as the unique ID (NO FILE EXTENSION).
id_: *camera_name
# Camera's unique ID.

data:
  type: "*.png"
  # Video file or image folder. By default, assume all video are put inside
  stream: null
  # If we run directly with the input stream, `stream` must be of some value.
  # By default, `null` means run with video file defined in `path`.
  shape: &shape [960, 1280, 3]
  # Input size as [H, W, C].
  frame_rate: &frame_rate 10
  # Frame rate of the video.
  process_num: 3
  # Number of processes which runs in parallel
  class_labels:
    file: "configs/class_labels_1cls.json"
    # Config file containing class_labels.

data_loader:
  data: "images"
  # Data source. Can be a path to an image file, a directory, a video, or
  # a stream. It can also be a pathname pattern to images.
  batch_size: &batch_size 10
  # Number of samples in one forward & backward pass.
  queue_size: *batch_size
  # Number of slot in the queue to store the frame
  data_dir_prefix: "tmot_dataset/images/val/"
  # Prefix of the dataset
#  data_dir_seq: ["seq2", "seq17", "seq22", "seq47", "seq54", "seq66"]
  data_dir_seq: ["seq2"]
  # Sequence of the dataset
  data_dir_postfix: "thermal/"
  # Postfix of the dataset

detector:
  name: "yolov8"
  # Name of the main model for detector
  model_cfg:
  # Detector model config.
    cfg: "yolov8s.yaml"
    # YOLOv5 variances.
    nc: 80
    # Number of classes.
  weights: "models_zoo/pbvs25_tmot/pbvs25_tmot_v1_1920/weights/best.pt"
  # Pretrained weights file.
  shape: [1600, 1600, 3]
  # Input size as [C, H, W].
  min_confidence: 0.0001
  # Detection confidence threshold. Disregard all detections that have a
  # confidence lower than this value.
  nms_max_overlap: 0.5
  # Maximum detection overlap (non-maxima suppression threshold).
  device: &device "0"
  # CUDDevice, i.e. 0 or 0,1,2,3 or cpu
  batch_size: *batch_size
  # Number of samples in one forward & backward pass.
  folder_out: "yolov8s_1600_imgz_1600"
  # The output folder
  queue_size: 30
  # Number of slot in the queue to store the detection result

tracker:
  name: "diffmot"
  # Name of the tracker.
  max_age: 10
  # Max number of frame keep the object before deleting.
  min_hit: 3
    # The number of frame which has matching bounding box of the detected object
  # before the object is considered becoming the track.
  iou_threshold: 0.2
  # The Intersection over Union between two track with their bounding box.
  folder_out: "diffmot"
  # The output folder
  weights: "models_zoo/pbvs25_tmot/pbvs25_tmot_1280/weights/best.pt"
  # Pretrained weights file.
  min_confidence_det: 0.2
  # Detection confidence threshold. Disregard all detections that have a
  # confidence lower than this value.
  is_reload_model: True
  # Does the tracking model need to be reset after running 1 sequence
  diffmot_config:
    eps: 0.001
    diffnet: HMINet
    encoder_dim: 256
    tf_layer: 3
    high_thres: 0.4
    low_thres: 0.1
    w_assoc_emb: 2.2
    aw_param: 1.7
    preprocess_workers: 16
    reid_dir: "/media/sugarubuntu/DataSKKU3/3_Dataset/PBVS_challenge/tmot_dataset_after_checked/output_pbvs25/tracking/diffmot/embeddings"

data_writer:
  output_dir: "/media/sugarubuntu/DataSKKU3/3_Dataset/PBVS_challenge/tmot_dataset_after_checked/output_pbvs25"
  # Output video file or a directory.
  shape: *shape
  # Output size [H, W, C].
  frame_rate: *frame_rate
  # Frame rate of the video.
  fourcc: "mp4v"
  # Video codec. One of: ["mp4v", "xvid", "mjpg", "wmv1"].
  queue_size: 30
  # Number of slot in the queue to store data for writer
  min_confidence: 0.2
  # Detection confidence threshold. Disregard all detections that have a
  # confidence lower than this value.
  final_file: "final_result.txt"
  # Name of file result file

...
